controller-deployment: add image secret option to yaml, add services …
RedisLabs/redislabs-helm pull request #2
Opened 2018-05-08 13:56 UTC by michalrabinowitch

…configuration values

-Allow pulling controller image from user defined repo (current pull is from public repo)
-Allow controller services to be configured: service type and service naming convention

2018-05-08 14:14 UTC, ushachar commented
Ticket # please...

2018-05-09 08:18 UTC, danni-m requested changes

2018-05-09 08:18 UTC, danni-m commented on redis-enterprise/values.yaml
> +redisControllerConfiguration:
Add documentation to README

2018-05-09 08:18 UTC, danni-m commented on redis-enterprise/values.yaml
> +#redisEnterpriseImagePullSecrets:
no need for double pull secrets

2018-05-09 14:28 UTC, michalrabinowitch commented
@danni-m pushed changes

2018-05-09 15:20 UTC, danni-m approved these changes

2018-05-09 15:22 UTC, danni-m approved these changes

2018-05-10 08:02 UTC, merged